### ISSUE TITLE
Support caching directory at Nginx CR

### ISSUE THREAD

**Issue by nettoclaudio** [tsuru/nginx-operator#10]
When configuring an effective cache on nginx web server, we will probably need to set up the `proxy_cache_path` to in-memory directory at filesystem, e.g. using a `tmpfs` mount.

Thus, I think we need to add a new string field at `NginxSpec` to store that cache path. At the first moment, a simple string it's enough but we could to store a slice of strings later.

```yaml
apiVersion: nginx.tsuru.io/v1alpha1
kind: Nginx
metadata:
  name: nginx-with-cache
spec:
  cachePath: /var/nginx/cache
```

When deployed into the Kubernetes cluster, the nginx-controller should to add a new [`EmptyVolumeSource`](https://godoc.org/k8s.io/api/core/v1#EmptyDirVolumeSource) with the `StorageMediumMemory` type at nginx's pod template.
